version: "3"
services:
  api:
    image: summerchen0101/development:v1.0.4
    env_file:
      - .env
    ports:
      - "80:8080"
    restart: unless-stopped
    # command: sh -c "yarn migrate deploy"
    links:
      - redis

  redis:
    image: redis

