version: "3"
services:
  api:
    image: summerchen0101/gamecity-api-dev:v1.0.0
    env_file:
      - .env
    ports:
      - "80:8080"
    restart: unless-stopped
    # command: sh -c "yarn migrate deploy"
