-- AlterTable
ALTER TABLE "Vip" ADD COLUMN     "withdraw_fee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "withdraw_fee_1" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "withdraw_fee_2" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "withdraw_fee_3" DOUBLE PRECISION NOT NULL DEFAULT 0;
