-- AlterTable
ALTER TABLE "GameRatio" ADD COLUMN     "water_duty" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Member" ADD COLUMN     "fee_duty" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "promotion_duty" DOUBLE PRECISION NOT NULL DEFAULT 0;
