export const GAME_MAINTENANCE_START = 'GAME_MAINTENANCE_START';
export const GAME_MAINTENANCE_END = 'GAME_MAINTENANCE_END';
export const MAIN_MAINTENANCE_START = 'MAIN_MAINTENANCE_START';
export const MAIN_MAINTENANCE_END = 'MAIN_MAINTENANCE_END';
